// arbor · init — scaffold arbor.config.mjs + qa/scenarios.mjs for a Cocos project. Discovers the
// clickable surface with `coir clickmap` (STATIC — no running game needed) so the `surface` starts
// pre-filled with the real button refs; the developer fills in the read-values, mechanics, spec, and
// webServer command. Turns "read the docs and hand-write a config" into "one command, tweak two lines".
import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { pkgBin } from './driver.mjs';

function findScene(root) {
  const skip = new Set(['node_modules', '.git', 'build', 'temp', 'library', 'arbor']);
  const walk = (dir, depth) => {
    if (depth > 5) return null;
    let ents; try { ents = readdirSync(dir); } catch { return null; }
    for (const e of ents) if (e.endsWith('.scene')) return join(dir, e);
    for (const e of ents) { if (skip.has(e) || e.startsWith('.')) continue; const p = join(dir, e); try { if (statSync(p).isDirectory()) { const f = walk(p, depth + 1); if (f) return f; } } catch { /* skip */ } }
    return null;
  };
  return walk(join(root, 'assets'), 0) || walk(root, 0);
}

export async function init(opts = {}) {
  const root = process.cwd();
  const cfgPath = join(root, 'arbor.config.mjs');
  if (existsSync(cfgPath) && !opts.force) { console.error('arbor.config.mjs already exists — pass --force to overwrite'); process.exit(1); }

  const scene = opts.scene || findScene(root);
  const coir = opts.coir || '../coir', copse = opts.copse || '../copse';
  const url = opts.url || 'http://127.0.0.1:8899/';

  // discover the wired buttons via coir clickmap (static)
  let buttons = [];
  if (scene) {
    const coirCli = process.env.COIR_CLI || pkgBin(join(root, coir), 'coir'); // coir's PUBLIC bin, not a guessed internal path
    try {
      const rows = JSON.parse(execFileSync('node', [coirCli, '-C', root, 'clickmap', relative(root, scene), '-o', 'json'], { encoding: 'utf8', maxBuffer: 64 << 20 }));
      buttons = rows.map((r) => ({ ref: r.nodePath.split('/').slice(1).join('/'), method: r.method }));
    } catch (e) { console.warn(`(coir clickmap couldn't read ${scene}: ${e.message} — the surface will be a bare template)`); }
  } else console.warn('(no .scene found — pass --scene <path>; the surface will be a bare template)');

  const surface = buttons.length
    ? `Buttons (op:press, ref):\n${buttons.map((b) => `  ${b.ref}   — TODO: what it does (wired to ${b.method})`).join('\n')}\n\nRead values (op:get, sel):  TODO — e.g. Canvas/Game:YourComponent.score | Canvas/ScoreLabel:Label.string\n\nMechanics:  TODO — animated / turn-based? then add {"op":"sleep","ms":N} after every press.`
    : 'TODO: list the buttons (op:press refs) and readable state (op:get sels), plus any mechanics the agent must know.';

  writeFileSync(cfgPath, CONFIG_TEMPLATE(url, coir, copse, scene ? relative(root, scene) : 'assets/scenes/main.scene', surface));
  mkdirSync(join(root, 'qa'), { recursive: true });
  if (!existsSync(join(root, 'qa/scenarios.mjs'))) writeFileSync(join(root, 'qa/scenarios.mjs'), SCENARIOS_TEMPLATE);

  console.log(`\n✓ arbor.config.mjs written — ${buttons.length} button(s) discovered via coir clickmap`);
  console.log('  next:');
  console.log('   1. set webServer.command (how to serve your build) + fill in surface (read-values + mechanics)');
  console.log('   2. npx arbor coverage --update   # seed the coverage baseline');
  console.log('   3. npx arbor visual --update     # seed the visual baseline (edit visual.refs first)');
  console.log('   4. npx arbor coverage            # the zero-LLM gate is live');
  console.log('   5. (AI) add a spec + surface details → npx arbor impact / verify');
  return { mode: 'init', failed: false };
}

const CONFIG_TEMPLATE = (url, coir, copse, scene, surface) => `// arbor.config.mjs — generated by \`arbor init\`. Fill in the TODOs.
import { defineConfig } from 'arbor';
import { scenarios } from './qa/scenarios.mjs';

export default defineConfig({
  url: '${url}',
  webServer: { command: 'TODO: how to serve your build, e.g. npx serve build/web-mobile -l 8899', reuseExisting: true },
  driver:   { copse: '${copse}' },
  analyzer: { coir:  '${coir}' },

  // ── zero-LLM gate ──
  scene: '${scene}',
  coverage: { baseline: './qa/coverage.json', rows: './qa/coir-rows.json' },
  visual:   { baseline: './qa/visual.json', refs: [/* TODO: nodePaths to pin visually, e.g. 'Canvas/PlayBtn' */] },

  // ── AI tier (optional) ──
  surface: \`${surface.replace(/`/g, '\\`')}\`,
  spec: null,        // TODO: './docs/game-design.md' — the oracle for \`verify\` / \`orchestrate\`
  scenarios,         // calibration scenarios (see qa/scenarios.mjs) — only needed for \`arbor calibrate\`
  reporters: ['console', 'json'],
});
`;

const SCENARIOS_TEMPLATE = `// qa/scenarios.mjs — calibration scenarios for \`arbor calibrate\` (a goal + the RNG pins that make its
// state reachable). Only needed if you have known bugs to measure detection against — a normal project
// leans on \`arbor impact\` / \`verify\` instead. Leave empty to skip \`calibrate\`.
export const scenarios = [
  // { id: 'my-check', bug: 'n/a', kind: 'semantic',
  //   pins: [{ sel: 'Canvas/Game:GameCtrl.rollX', replace: '()=>true' }],
  //   goal: 'Drive <the flow> and verify <the invariant>.' },
];
`;
